version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: analytics-node
    versions:
    - 4.0.0
  - dependency-name: eslint-plugin-mocha
    versions:
    - 8.0.0
  - dependency-name: semver
    versions:
    - 7.3.4
